### ISSUE TITLE
@conda-forge-admin, please restart ci

### ISSUE THREAD

**Issue by oskar-maier-ms** [conda-forge/medpy-feedstock#14]
### Additional comment:

Previous builds all failed due to connectivity issues.

**Comment by oskar-maier-ms** [comment]
I am not quite sure if this is the way to re-start the Azure build process. I struggle finding information on the topic. Any idea @sarthakpati ?

**Comment by sarthakpati** [comment]
I unfortunately do not. 😞 

The best I can do would be to point you to the conda-forge community pages: https://conda-forge.org/community/getting-in-touch/#gitter-and-element

Please LMK if there is anything I can do to help.

**Comment by oskar-maier-ms** [comment]
Thanks! I'll then just increase the build number in the recipe to trigger a new merge and build. That should work (I hope).
